[tables]

[tables.churn]

[tables.churn.path]
raw_local = "C:\\learn_ml_gcp\\ML_with_GCP\\data\\raw.csv"
raw_gcs = "gs://telco-churn-data-test/raw.csv"

[tables.churn.schema]
target = "Churn"

[tables.churn.schema.columns]
'gender' = 'object'
'SeniorCitizen' = 'int64'
'Partner' = 'object'
'Dependents' = 'object'
'tenure' = 'int64'
'PhoneService' = 'object'
'MultipleLines' = 'object'
'InternetService' = 'object'
'OnlineSecurity' = 'object'
'OnlineBackup' = 'object'
'DeviceProtection' = 'object'
'TechSupport' = 'object'
'StreamingTV' = 'object'
'StreamingMovies' = 'object'
'Contract' = 'object'
'PaperlessBilling' = 'object' 
'PaymentMethod' = 'object'
'MonthlyCharges' = 'float64'
'TotalCharges' = 'float64'
'Churn' = 'object'